//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Natacha_Projet_802
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produits
    {
        public int ProduitID { get; set; }
        public string NomProduit { get; set; }
        public Nullable<int> CategorieID { get; set; }
        public string QuantiteParUnite { get; set; }
        public Nullable<decimal> PrixUnite { get; set; }
        public Nullable<short> UnitesEnStock { get; set; }
        public Nullable<short> UnitesSurCommande { get; set; }
        public bool Discontinu { get; set; }
    
        public virtual Categories Categories { get; set; }
    }
}
